### ISSUE TITLE
link on pypi is not working

### ISSUE THREAD

**Issue by johanneswilm** [executablebooks/sphinx-autobuild#102]
The link on pypi leads to https://github.com/GaretJax/sphinx_autobuild . Clicking it leads to a 404 message. It should apparently go to executablebooks/sphinx-autobuild.

**Comment by jasongrout** [comment]
It looks like this was solved in #98.

**Comment by tnwei** [comment]
Yup it is solved, heads up that this issue can be closed

**Comment by choldgraf** [comment]
Thanks for noting!
