### ISSUE TITLE
Allow installing pip modules (requirements.txt) from repo

### ISSUE THREAD

**Issue by ibotty** [executablebooks/sphinx-autobuild#111]
### Description / Summary

It would be great if sphinx-autobuild could install modules from `requirements.txt` automatically and when the file changes.

### Value / benefit

I am offering development-containers running in a cloud for people writing documentation.  Apart from the known issues it works great.  But installing sphinx modules via pip is not as easy for them.

**Comment by pradyunsg** [comment]
You can do this with a pre-build command. This is done by passing `--pre-build` to sphinx-autobuild.

```
sphinx-autobuild --pre-build "path/to/venv/bin/pip install magic" ...
```
