### ISSUE TITLE
Maintenance backup - I'd be happy to help a bit

### ISSUE THREAD

**Issue by consideRatio** [executablebooks/sphinx-autobuild#121]
Hi!

I thought it was really cool that this project was part of executablebooks and ended up looking through some stale PRs that can be easily merged I think.

If you want some backup, I'd be happy to help out a bit. I'm an active maintainer in the jupyterhub github organization and has been active in open source for a bit more than five years now.

**Comment by choldgraf** [comment]
I've invited you as a maintainer in this repository - thanks so much @consideRatio ♥️
