### ISSUE TITLE
Share credentials to push this to PyPI with the `executablebooks/` steering council

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-autobuild#126]
This repository was set up with PyPI before being transferred into the `executablebooks/` org. In order to be able to make releases, we need to share the credentials to publish to PyPI with others in the group.

- [Here's the link to the PyPI page for this package](https://pypi.org/project/sphinx-autobuild/)
- The two maintainers listed there are @pradyunsg and @GaretJax 

Could one of you please add at least the https://pypi.org/user/ebp-bot/ and ideally also any other EBP members that might be able to help with releases?

**Comment by pradyunsg** [comment]
Invited the bot. Let me know if there's any other stuff that needs to be done. :)

**Comment by choldgraf** [comment]
Thanks! Now we just need to:

- https://github.com/executablebooks/team-compass/issues/10

😅

**Comment by pradyunsg** [comment]
Let's track that there. :)

**Comment by choldgraf** [comment]
Indeed - although depending on who has access to that account we might need to re-send credentials to sphinx-autobuild (if it expires). Feel free to invite me as well and then I can invite others in the EB team as needed so we don't block on that.
