### ISSUE TITLE
On Windows, text after errors occur is black-on-black

### ISSUE THREAD

**Issue by toolness** [executablebooks/sphinx-autobuild#54]
I'm not sure if this is specifically a sphinx-autobuild problem or something that's due to a dependency or my system configuration, but I've noticed that when I run sphinx-autobuild on a Windows 10 system, all text after an error occurs is black text on a black background:

![2017-05-16_14-04-58](https://cloud.githubusercontent.com/assets/124687/26121029/d9a62c18-3a40-11e7-8d8a-5f8fb1c2ac2e.png)

I've tried changing the settings of my terminal so that e.g. my default background color isn't black, but that doesn't seem to help.

Whenever another error occurs, it *does* show up in red-on-black, but the text after it reverts to being black-on-black too.

**Comment by pradyunsg** [comment]
Thanks for reporting this! ^>^

Could someone confirm whether this behavior is visible with the current versions of Sphinx and `sphinx-autobuild`? In case it's not, I'm inclined to close this in a week or so, if no one flags this as still-a-problem.

**Comment by strefli3** [comment]
I can verify that is is still a problem on windows 10 in git-bash, but I am stuck on these versions for the foreseeable future: 
```
Sphinx==3.2.1
sphinx-autobuild==0.7.1
```

**Comment by jjyyxx** [comment]
Have this too. Use `-N` flag or change 
https://github.com/executablebooks/sphinx-autobuild/blob/274445aba3c4bc75458f1a4c6b83f1e501fc71d4/src/sphinx_autobuild/utils.py#L50-L52

to

```python
stdout = subprocess.Popen(
    args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True
).stdout
```

seems to workaround the issue. However, both methods lose color for stderr.

**Comment by pradyunsg** [comment]
I'm pretty sure I fixed this when I reworked the output handling of this project. If someone is still seeing this, please file a new issue. :)
