### ISSUE TITLE
Maintainance status -- new release soon!

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-autobuild#81]
Hey @GaretJax!

I see that this package hasn't been updated in a while. Is this still actively maintained? If not, would you be OK with transferring maintainership of this project to someone else (either an individual - I am happy to volunteer for that - or an org like jazzband or executablebooks)?

**Comment by chrisjsewell** [comment]
Yes we at https://github.com/executablebooks would most probably be happy to take it on

**Comment by chrisjsewell** [comment]
And obviously still set you as an one of the owners

**Comment by GaretJax** [comment]
Hi @pradyunsg, thanks for the offer. I think there have been talks between @evildmp and jazzband in the past about this, but I don't know what the status is there; that would be my preferred solution.

I didn't know about executablebooks @chrisjsewell, but it looks like you do a lot of sphinx indeed, so it may be even a better home.

**Comment by chrisjsewell** [comment]
oh yes a lot lol! and @pradyunsg has been helping us out on the web design side of things which is obviously where this package comes in very handy. We're just integrating into our development process (see https://github.com/executablebooks/sphinx-book-theme/pull/172) so would certainly like to keep it active.

But yeh naturally its entirely up to you, but just let us know if you do want to and I wouldn't foresee any objections 😄

**Comment by GaretJax** [comment]
Could we start maybe by adding @pradyunsg (and you @chrisjsewell, don't know how you're organized) to this repo and see how things go? If all goes well, I'm then happy to transfer it to another org.

**Comment by chrisjsewell** [comment]
yep no problem, sounds good to me 👍

**Comment by GaretJax** [comment]
Who shall I add?

**Comment by chrisjsewell** [comment]
@pradyunsg you opened the issue so should have first refusal 😊

**Comment by pradyunsg** [comment]
Sounds great to me!

Please feel free to add me (and @chrisjsewell, if they say they're OK with it) here and we'll take it from there. :)

**Comment by GaretJax** [comment]
@pradyunsg you have access as a collaborator to the repo.

**Comment by pradyunsg** [comment]
Oh awesome! Thank you! ^.^

My next instinctive question is, PyPI access. Would you be willing to give me publish access on PyPI as well? (same username there, https://pypi.org/user/pradyunsg/)

**Comment by chrisjsewell** [comment]
Well we could just move the testing/deployment to GitHub actions.
Then it just requires an API secret being set on the repository 😉 

(like https://github.com/executablebooks/MyST-Parser/blob/master/.github/workflows/tests.yml)

**Comment by pradyunsg** [comment]
We certainly can/should do that, but my concern stems more from a bus factor perspective for this project. :)

**Comment by GaretJax** [comment]
I'll give you access in due course @pradyunsg ;-)

**Comment by pradyunsg** [comment]
Sounds fair to me! ^>^

**Comment by choldgraf** [comment]
Damn we will have to refactor our plans to install crypto miners in everybody's Sphinx builds 😅

but seriously - thanks @GaretJax for inviting collaboration on this repo!

**Comment by pradyunsg** [comment]
LOL

I'm pretty sure we have access to better "targets" if we really wanted to spread crypto miners around. 😂

**Comment by GaretJax** [comment]
I knew it!

**Comment by pradyunsg** [comment]
Ahoy @GaretJax! I think we're almost ready for a release.

- Would you be willing to transfer the project to the executablebooks organization?
- PyPI access would be nice to have, to actually make the release. 🙃

**Comment by pradyunsg** [comment]
#93 and #94 await @GaretJax's OK (and PyPI access).

**Comment by pradyunsg** [comment]
> Oh and I also expect you to use myst-parser and sphinx-book-theme for the RTD docs 😉

I don't think this project needs RTD docs. :)

**Comment by GaretJax** [comment]
@pradyunsg you have been granted access to PyPI and I approved the two PRs.
I tried to transfer the project but I don't have the rights to create public repos on the executablebooks organisation. It also does not seem possible to grant you more privileges as what you already have here. I also tried to transfer the ownership to yourself (so that you can transfer it to the org), but you already have a fork of the repo.

**Comment by chrisjsewell** [comment]
@GaretJax I've just invited you as a member of executablebooks 😄

**Comment by GaretJax** [comment]
Transferred!

**Comment by chrisjsewell** [comment]
🎉 thanks, @pradyunsg we can start crypto mining 😂

**Comment by chrisjsewell** [comment]
@pradyunsg I just gave you maintainer status

**Comment by pradyunsg** [comment]
@chrisjsewell Could you make me an admin -- I can't see webhooks and don't have the ability to manage protected branches.

**Comment by pradyunsg** [comment]
> @pradyunsg you have been granted access to PyPI and I approved the two PRs.

Awesome! Thank you @GaretJax! ^>^

**Comment by pradyunsg** [comment]
Note to self: make a release on 1st. :)

**Comment by pradyunsg** [comment]
sphinx-autobuild 2020.9.1 is out! We're golden. Now, let's see if people report breakages, or if anyone complains. :)

**Comment by pradyunsg** [comment]
Thanks everyone here! Definitely wouldn't have happened without y'all. ^>^

**Comment by GaretJax** [comment]
Thank you @pradyunsg for resurrecting the project! :heart:
