### ISSUE TITLE
Use meaningfull commit messages

### ISSUE THREAD

**Issue by return42** [executablebooks/sphinx-autobuild#97]
**Is your feature request related to a problem? Please describe.**

We have a lot of meaningless commit messages in the last time.

**Describe the solution you'd like**

About this topic, there are a lot of articles around in the net. I fond this one concise: https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message

**Describe alternatives you've considered**

The alternative is what we have, describing what is obvious e.g.: 9fc794e8 saying "Drop setup.py"  but no information what the intention is.

**Additional context**

Having a story in your git log will make a huge difference in how you and others perceive your project. By taking great care in commit messages, as you do in your code, you will help to increase overall quality.

**Comment by pradyunsg** [comment]
Thanks for filing this issue! Duly noted and will keep in mind going forward.

FWIW, all the relevant context is in the PR that contains this commit - https://github.com/executablebooks/sphinx-autobuild/pull/83.

> Having a story in your git log will make a huge difference in how you and others perceive your project.  

The commit that's immediately after this one is "Add flit configuration" which does indeed tell the story that it's supposed to. 🤷🏻‍♂️

As for the meta discussion of good commit messages - they take time to write and for something like this, I don't consider that to be worth the investment given that there's sufficient reasoning provided via context (in this case the PR). Of course, we all don't have the same shared context tho, so, I'll keep that in mind going forward.

**Comment by return42** [comment]
> I'll keep that in mind going forward.

Thanks!
